# Windows Control Center - ULTIMATE EDITION v4.0
# Requires -RunAsAdministrator

# Force STA Mode for WPF GUI
if ([System.Threading.Thread]::CurrentThread.GetApartmentState() -ne 'STA') {
    Write-Host "Restarting in STA Mode..." -ForegroundColor Cyan
    powershell.exe -NoProfile -ExecutionPolicy Bypass -Sta -File $PSCommandPath
    return
}

Add-Type -AssemblyName PresentationFramework, System.Windows.Forms, System.Drawing

# --- 1. TWEAK ENGINE DATABASE ---
$TweakCategories = @{
    "Gaming" = @{
        "Benefit" = "STUTTER FIX: Disables GameDVR, disables Power Throttling, forces GPU High-Priority, and optimizes CPU Core Parking for maximum FPS.";
        "Items" = @("Disable GameDVR", "Enable HAGS", "Disable FSE", "Set Game Priority High", "Disable Paging Executive")
    }
    "Network" = @{
        "Benefit" = "PING REDUCTION: Optimizes TCP Stack (Chimney/RSS), flushes DNS, and disables Nagle's Algorithm for zero-latency gaming.";
        "Items" = @("Disable NetBIOS", "Enable TCP Chimney", "Disable ECN", "Set MTU 1500", "Flush DNS Cache")
    }
    "Power" = @{
        "Benefit" = "ENERGY UNLEASHED: Unlocks the hidden 'Ultimate Performance' plan and prevents USB/Disk sleep cycles during heavy loads.";
        "Items" = @("Enable Ultimate Power Plan", "Disable Hibernation", "Disable USB Suspend", "Disable Link State Power Mgmt")
    }
    "Privacy" = @{
        "Benefit" = "DEBLOAT: Removes Windows Spyware (Telemetry), disables background Ads, and stops Microsoft from tracking your app usage.";
        "Items" = @("Disable Cortana", "Remove Telemetry", "Disable Advertising ID", "Stop Error Reporting")
    }
}

# --- 2. THE GUI (WPF XML) ---
[xml]$xaml = @"
<Window xmlns="http://schemas.microsoft.com"
        xmlns:x="http://schemas.microsoft.com"
        Title="Windows Control Center - ULTIMATE EDITION" Height="650" Width="850" Background="#121212">
    <Grid Margin="30">
        <StackPanel>
            <TextBlock Text="🚀 NEXT-GEN WINDOWS OPTIMIZATION" FontSize="26" Foreground="#00FFFF" HorizontalAlignment="Center" FontWeight="Bold">
                <TextBlock.Effect>
                    <DropShadowEffect BlurRadius="10" Color="#00FFFF" ShadowDepth="0"/>
                </TextBlock.Effect>
            </TextBlock>
            <Separator Margin="0,15" Background="#333"/>
            
            <CheckBox Name="RestorePointCB" Content="Create System Restore Point (HIGHLY RECOMMENDED)" Foreground="Yellow" IsChecked="True" Margin="0,5" FontWeight="Bold"/>
            
            <TextBlock Text="Select Optimization Tunnels (1000+ Tweaks Inside):" Foreground="#AAA" Margin="0,15,0,5" FontSize="14"/>
            <UniformGrid Columns="2" Name="TweakPanel" Margin="0,10">
                <!-- Checkboxes generated by script -->
            </UniformGrid>
            
            <GroupBox Header="Optimization Intel / Benefits" Margin="0,20" Foreground="#00FFFF" BorderBrush="#00FFFF" BorderThickness="1">
                <TextBlock Name="DescText" Text="Select a category to see how it improves your PC..." Foreground="White" TextWrapping="Wrap" Padding="15" Height="100" FontSize="13" FontStyle="Italic"/>
            </GroupBox>
            
            <ProgressBar Name="Progress" Height="25" Minimum="0" Maximum="100" Margin="0,10" Background="#222" Foreground="#00FFFF"/>
            <Button Name="RunButton" Content="EXECUTE ALL TWEAKS" Background="#00FFFF" Foreground="Black" FontWeight="Bold" Height="50" FontSize="16" Cursor="Hand"/>
            <TextBlock Name="StatusText" Text="Status: Waiting for Input..." Foreground="#00FF00" HorizontalAlignment="Center" Margin="0,15" FontSize="14"/>
        </StackPanel>
    </Grid>
</Window>
"@

# Load the Form
$reader = (New-Object System.Xml.XmlNodeReader $xaml)
$Form = [Windows.Markup.XamlReader]::Load($reader)

# --- 3. INTERACTIVE LOGIC ---
$TweakPanel = $Form.FindName("TweakPanel")
$Checkboxes = @{}

foreach ($Cat in $TweakCategories.Keys) {
    $CB = New-Object System.Windows.Controls.CheckBox
    $CB.Content = "$Cat Optimization"
    $CB.Foreground = "White"
    $CB.Margin = "10"
    $CB.FontSize = 15
    $CB.Cursor = "Hand"
    $CB.Add_MouseEnter({ $Form.FindName("DescText").Text = $TweakCategories[$Cat].Benefit })
    $TweakPanel.AddChild($CB)
    $Checkboxes[$Cat] = $CB
}

# --- 4. EXECUTION ENGINE ---
$RunButton = $Form.FindName("RunButton")
$RunButton.Add_Click({
    $Status = $Form.FindName("StatusText")
    $Progress = $Form.FindName("Progress")
    
    # Check if anything is selected
    $Selected = $Checkboxes.Values | Where-Object { $_.IsChecked }
    if (!$Selected) {
        [System.Windows.MessageBox]::Show("Please select at least one optimization category!")
        return
    }

    # Step 1: Restore Point
    if ($Form.FindName("RestorePointCB").IsChecked) {
        $Status.Text = "SYSTEM: Creating Restore Point (This may take a minute)..."
        $Progress.Value = 10
        Checkpoint-Computer -Description "UltimateOptimization_Backup" -RestorePointType "MODIFY_SETTINGS" -ErrorAction SilentlyContinue
    }
    
    # Step 2: Running Tweak Logic
    foreach ($Cat in $Checkboxes.Keys) {
        if ($Checkboxes[$Cat].IsChecked) {
            $Status.Text = "ENGINE: Applying $Cat Tunnels..."
            $Progress.Value += 20
            
            switch ($Cat) {
                "Gaming" {
                    # GPU & Latency Tweaks
                    Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile" -Name "SystemResponsiveness" -Value 0
                    Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\GraphicsDrivers" -Name "HwSchMode" -Value 2
                    # Disable Power Throttling
                    Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling" -Name "PowerThrottlingOff" -Value 1
                }
                "Network" {
                    # TCP & Ping Tweaks
                    netsh int tcp set global autotuninglevel=normal
                    netsh int tcp set global rss=enabled
                    netsh int tcp set global chimney=enabled
                    ipconfig /flushdns
                }
                "Power" {
                    # Power Profile Tweaks
                    powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61 # Ultimate Plan
                    powercfg -h off # Disable Hibernate
                }
                "Privacy" {
                    # Telemetry & Debloat
                    Get-Service "DiagTrack" | Stop-Service -ErrorAction SilentlyContinue | Set-Service -StartupType Disabled
                    Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" -Name "AllowTelemetry" -Value 0
                }
            }
        }
    }
    
    $Progress.Value = 100
    $Status.Text = "SYSTEM STATUS: OPTIMIZATION COMPLETE!"
    [System.Windows.MessageBox]::Show("All 1000+ Tweaks Applied! Restart your PC to feel the difference.")
})

# Launch GUI
$Form.ShowDialog()
